version: '3.8'
services:
  app:
    image: my-java-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FORCE_REBUILD: ${FORCE_REBUILD:-1}
    ports:
      - "8080:8080"
    environment:
      - DOCKER_ENV=true
