version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:7.17.5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - TZ=Europe/Amsterdam
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.5
    environment:
      - TZ=Europe/Amsterdam
      - SERVER_NAME=127.0.0.1
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - "5601:5601"

  app:
    image: my-java-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FORCE_REBUILD: ${FORCE_REBUILD:-1}
    ports:
      - "8080:8080"
    environment:
      - DOCKER_ENV=true
    depends_on:
      - elasticsearch  # Ensure the app starts after Elasticsearch
